services:
  flask_app:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/app_db
    expose:
      - "5000"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    environment:
      - PORT=5000
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - flask_app

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
