services:
  flask_app:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      - DB_PORT=27017
      - DB_URL=mongo
      - PORT=5000
    expose:
      - "5000"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    environment:
      - PORT=5000
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - flask_app

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
