apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
  labels:
    app: mongodb-headless-service
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
