# mongodb-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb-pod
spec:
  containers:
    - name: mongodb
      image: mongodb:latest  # Use a specific version if needed
      imagePullPolicy: Never  # Use the local image
      ports:
        - containerPort: 27017
      resources:
        requests:
          memory: "100Mi"
          cpu: "1"
        limits:
          memory: "200Mi"
          cpu: "2"
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db  # Default MongoDB data directory
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: mongodb-pvc
