apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1  # Single replica for MongoDB
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest  # Use a specific version if needed
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "100Mi"
              cpu: "1"
            limits:
              memory: "200Mi"
              cpu: "2"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db  # Default MongoDB data directory
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
