apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-proxy
      image: nginx_proxy:latest
      imagePullPolicy: Never
      resources:
        requests:
          memory: "100Mi"
          cpu: "1"
        limits:
          memory: "200Mi"
          cpu: "2"
      ports:
        - containerPort: 80  # Nginx exposed port
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
