apiVersion: v1
kind: Pod
metadata:
  name: shopping-api
spec:
  serviceAccountName: development-api # Using service account
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - image: nginx
    name: shopping-api
    resources:
        requests:
          memory: "100Mi"
          cpu: "1"
        limits:
          memory: "200Mi"
          cpu: "2"
