apiVersion: v1
kind: ResourceQuota
metadata:
  name: ps-quota
  namespace: development
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "5Gi"
    limits.cpu: "20"
    limits.memory: "10Gi"
    pods: "10"
  scopes:
    - NotTerminating
    - NotBestEffort