apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shopping-api
  namespace: development
subjects:
- kind: ServiceAccount
  name: development-api
roleRef:
  kind: Role
  name: shopping-api-role
  apiGroup: rbac.authorization.k8s.io
